apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubelet-csr-approver
  namespace: kubelet-csr-approver
spec:
  interval: 5m
  chart:
    spec:
      chart: kubelet-csr-approver
      sourceRef:
        kind: HelmRepository
        name: kubelet-csr-approver
        namespace: kubelet-csr-approver
  values:
    providerIpPrefixes:
      - 10.1.1.0/24
    providerRegex: ^(mini|z)$
    bypassDnsResolution: true
