apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubelet-csr-approver
  namespace: kubelet-csr-approver
spec:
  interval: 1h
  url: https://postfinance.github.io/kubelet-csr-approver
