apiVersion: apps/v1
kind: Deployment
metadata:
  name: resolve-db
  namespace: resolve-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resolve-db
  template:
    metadata:
      labels:
        app: resolve-db
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: postgres
          image: postgres:18
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: DaVinciResolve
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: resolve-db-credentials
                  key: password
            - name: POSTGRES_DB
              value: DaVinciResolve
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 1Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: resolve-db-data
