apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: resolve-db-credentials
  namespace: resolve-db
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: resolve-db-credentials
  data:
    - secretKey: password
      remoteRef:
        key: resolve-db_resolve-db-credentials/password
