apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resolve-db-data
  namespace: resolve-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-synology
  resources:
    requests:
      storage: 50Gi
