apiVersion: v1
kind: Service
metadata:
  name: resolve-db
  namespace: resolve-db
spec:
  type: LoadBalancer
  selector:
    app: resolve-db
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
