apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-postgres
  namespace: immich
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: immich-postgres
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: immich_immich-postgres/POSTGRES_DB
    - secretKey: POSTGRES_USER
      remoteRef:
        key: immich_immich-postgres/POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: immich_immich-postgres/POSTGRES_PASSWORD
