apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres-iscsi
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi
  resources:
    requests:
      storage: 20Gi
