apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
spec:
  storageClassName: nfs-synology
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
