apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 5m
  chart:
    spec:
      chart: immich
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: immich
  values:
    immich:
      persistence:
        library:
          existingClaim: immich-library

    controllers:
      main:
        containers:
          main:
            env:
              DB_URL: "postgresql://immich:immich@immich-postgres:5432/immich"

    server:
      enabled: true

    machine-learning:
      enabled: true
      runtimeClassName: nvidia
      persistence:
        cache:
          enabled: true
          storageClass: local-path
          size: 10Gi
      resources:
        limits:
          nvidia.com/gpu: 1
      nodeSelector:
        nvidia.com/gpu: "true"

    valkey:
      enabled: true
