apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: controld-api-key
  namespace: controld-exporter
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: controld-api-key
  data:
    - secretKey: api-key
      remoteRef:
        key: controld-exporter/controld-api-key
        property: api-key
