apiVersion: v1
kind: Service
metadata:
  name: controld-exporter
  namespace: controld-exporter
  labels:
    app: controld-exporter
spec:
  selector:
    app: controld-exporter
  ports:
    - port: 10034
      targetPort: 10034
      protocol: TCP
