apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates:
        - GPU
    permittedHostDevices:
      pciHostDevices:
        - pciVendorSelector: "10de:"
          resourceName: nvidia.com/gpu-passthrough
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  infra:
    nodePlacement:
      nodeSelector:
        kubernetes.io/arch: amd64
  workloads:
    nodePlacement:
      nodeSelector:
        kubernetes.io/arch: amd64
  workloadUpdateStrategy: {}
