apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-models
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-synology
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-outputs
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-synology
  resources:
    requests:
      storage: 10Gi
