apiVersion: apps/v1
kind: Deployment
metadata:
  name: bedrock
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bedrock
  template:
    metadata:
      labels:
        app: bedrock
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: bedrock
          image: itzg/minecraft-bedrock-server:2026.9.0
          ports:
            - containerPort: 19132
              protocol: UDP
          env:
            - name: EULA
              value: "TRUE"
            - name: SERVER_NAME
              value: "wrtk8s"
            - name: GAMEMODE
              value: creative
            - name: DIFFICULTY
              value: normal
            - name: ALLOW_CHEATS
              value: "true"
            - name: MAX_PLAYERS
              value: "10"
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 2Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bedrock-data
