apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: playit-secret
  namespace: minecraft
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: playit-secret
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: minecraft_playit-secret
        property: SECRET_KEY
