apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - external-secret.yaml
  - playit-deployment.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - java-pvc.yaml
  - java-deployment.yaml
  - java-service.yaml
