apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcadmin-data
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-synology
  resources:
    requests:
      storage: 1Gi
