apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rcon-secret
  namespace: minecraft
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: rcon-secret
  data:
    - secretKey: password
      remoteRef:
        key: minecraft_rcon-secret/password
