apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nvidia-device-plugin
  namespace: nvidia-system
spec:
  interval: 1h0m0s
  url: https://nvidia.github.io/k8s-device-plugin
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: nvidia-system
spec:
  interval: 5m
  chart:
    spec:
      chart: nvidia-device-plugin
      sourceRef:
        kind: HelmRepository
        name: nvidia-device-plugin
        namespace: nvidia-system
  values:
    runtimeClassName: nvidia
    nodeSelector:
      nvidia.com/gpu: "true"
    config:
      map:
        default: |-
          version: v1
          sharing:
            timeSlicing:
              resources:
                - name: nvidia.com/gpu
                  replicas: 2
        mini: |-
          version: v1
          sharing:
            timeSlicing:
              resources:
                - name: nvidia.com/gpu
                  replicas: 4
        spark: |-
          version: v1
          sharing:
            timeSlicing:
              resources:
                - name: nvidia.com/gpu
                  replicas: 2
    gfd:
      enabled: true
