apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: nvidia-system
spec:
  interval: 5m
  chart:
    spec:
      chart: nvidia-device-plugin
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: nvidia-system
  values:
    runtimeClassName: nvidia
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: nvidia.com/gpu
                  operator: In
                  values:
                    - "true"
    config:
      map:
        default: |-
          version: v1
          sharing:
            timeSlicing:
              resources:
                - name: nvidia.com/gpu
                  replicas: 2
