apiVersion: v1alpha1
kind: StaticHostConfig
name: 10.1.1.158
hostnames:
  - cr.jgarr.net
---
apiVersion: v1alpha1
kind: StaticHostConfig
name: 10.1.1.162
hostnames:
  - k8s.cr.jgarr.net
---
apiVersion: v1alpha1
kind: StaticHostConfig
name: 10.1.1.161
hostnames:
  - ghcr.cr.jgarr.net
---
apiVersion: v1alpha1
kind: StaticHostConfig
name: 10.1.1.159
hostnames:
  - docker.cr.jgarr.net
---
apiVersion: v1alpha1
kind: StaticHostConfig
name: 10.1.1.160
hostnames:
  - gcr.cr.jgarr.net
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: docker.io
endpoints:
  - url: https://docker.cr.jgarr.net
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: ghcr.io
endpoints:
  - url: https://ghcr.cr.jgarr.net
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: registry.k8s.io
endpoints:
  - url: https://k8s.cr.jgarr.net
