apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepassword:
      connectHost: https://connect.1password.com
      vaults:
        wrtk8s: 1
      auth:
        secretRef:
          serviceAccountToken:
            name: onepassword-token
            namespace: external-secrets
            key: token
