apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dcgm-exporter
  namespace: dcgm-exporter
spec:
  interval: 5m
  chart:
    spec:
      chart: dcgm-exporter
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: dcgm-exporter
  values:
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
    runtimeClassName: nvidia
