apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - net-attach-def.yaml
  - ubuntu-boot-pv.yaml
  - ubuntu-cloudinit.yaml
  - ubuntu-smb-credentials.yaml
  - ubuntu-vm.yaml
