apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu
  namespace: kubevirt
spec:
  running: true
  dataVolumeTemplates: []
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      priorityClassName: kubevirt-cluster-critical
      nodeSelector:
        kubernetes.io/hostname: 3d
      domain:
        cpu:
          cores: 4
        resources:
          requests:
            memory: 12Gi
        devices:
          gpus:
            - name: gpu
              deviceName: nvidia.com/gpu-passthrough
          interfaces:
            - name: default
              masquerade: {}
            - name: lan
              macAddress: "9a:85:55:74:10:98"
              bridge: {}
          disks:
            - name: boot
              disk:
                bus: virtio
            - name: smb-credentials
              disk:
                bus: virtio
              serial: SMBCREDS
            - name: cloudinit
              disk:
                bus: virtio
      networks:
        - name: default
          pod: {}
        - name: lan
          multus:
            networkName: br0
      volumes:
        - name: boot
          persistentVolumeClaim:
            claimName: ubuntu-boot-local
        - name: smb-credentials
          secret:
            secretName: ubuntu-smb-credentials
        - name: cloudinit
          cloudInitNoCloud:
            secretRef:
              name: ubuntu-cloudinit
