apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: benchy
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: disk.transport == "sata"
---
machine:
  install:
    extraKernelArgs:
      - hugepagesz=1G
      - hugepages=4
      - default_hugepagesz=1G
