apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: pi5-1
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: disk.transport == "nvme"
  maxSize: 50GiB
  grow: false
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-path
provisioning:
  diskSelector:
    match: disk.transport == "nvme"
  minSize: 100GiB
  grow: true
