apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 1h0m0s
  url: oci://ghcr.io/home-assistant/charts
  type: oci
