apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bambustudio-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-synology
  resources:
    requests:
      storage: 10Gi
