apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotify-data
  namespace: gotify
spec:
  storageClassName: synology-iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
