apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.yaml
  - nfs-volumes.yaml
  - mariadb.yaml
  - deployment.yaml
  - ingress.yaml
  - tailscale-ingress.yaml
