apiVersion: v1
kind: PersistentVolume
metadata:
  name: romm-roms
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
  nfs:
    server: 10.1.1.4
    path: /volume1/public/install/games/ROMS
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-roms
  namespace: romm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: romm-roms
  resources:
    requests:
      storage: 1Ti
