apiVersion: v1
kind: Secret
metadata:
  name: romm-credentials
  namespace: romm
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: romm-root-secret
  MARIADB_DATABASE: romm
  MARIADB_USER: romm
  MARIADB_PASSWORD: romm-db-secret
  DB_HOST: romm-db
  DB_NAME: romm
  DB_USER: romm
  DB_PASSWD: romm-db-secret
  ROMM_AUTH_SECRET_KEY: 851e2675bb1944f77450f1c0bc4aad68b16cb41e54f41179075501831f6fe6aa
