apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 1h
  chart:
    spec:
      chart: metallb
      version: ">=0.15.0"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb-system
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  values:
    speaker:
      ignoreExcludeLB: true
