apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudnative-pg
  - cert-manager
  - controld-exporter
  - descheduler
  - external-dns
  - external-secrets
  - flannel
  - flux-system
  - frigate
  - headlamp
  - hockeytime
  - home-assistant
  - immich
  - keda
  - kepler
  - kubelet-csr-approver
  - kvmm
  - local-path-provisioner
  - mealie
  - metallb
  - metrics-server
  - minecraft
  - mistral-system
  - miniflux
  - n8n
  - tenstorrent-system
  - monitoring
  - mqtt
  - nfs-csi

  - nvidia-system

  - omni-cd
  - paperless-ngx
  - reaparr
  - registry
  - resolve-db
  - reloader
  - rpi-led-daemon
  - tailscale-operator
  - timesync
  - tts
  - talos-remote-config
  - traefik
  - vllm-system
  - whisper-webui
  - youtarr
  - arm
  - audiomass
  - bambustudio
  - gitea
  - pdfcraft
  - plex
  - pulsys
