apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudnative-pg
  - cert-manager
  - dcgm-exporter
  - descheduler
  - external-dns
  - flannel
  - flux-system
  - frigate
  - headlamp
  - home-assistant
  - immich
  - kubelet-csr-approver
  - kubevirt
  - kvmm
  - local-path-provisioner
  - metallb
  - multus
  - metrics-server
  - minecraft
  - miniflux
  - monitoring
  - mqtt
  - nfs-csi

  - nvidia-system

  - omni-cd
  - reaparr
  - romm
  - registry
  - resolve-db
  - reloader
  - tailscale-operator
  - tts
  - talos-remote-config
  - traefik
  - vllm-system
  - whisper-webui
  - plex
