---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: metallb
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: metallb-system
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged

    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      metadata:
        name: metallb
        namespace: metallb-system
      spec:
        interval: 10m0s
        url: https://metallb.github.io/metallb

    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: metallb
        namespace: metallb-system
      spec:
        interval: 1h
        releaseName: metallb
        chart:
          spec:
            chart: metallb
            # renovate: datasource=helm depName=metallb registryUrl=https://metallb.github.io/metallb
            version: 0.15.3
            sourceRef:
              kind: HelmRepository
              name: metallb
        values:
          speaker:
            ignoreExcludeLB: true

---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: metallb-config
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  resources:
    - apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        creationTimestamp: null
        name: default
        namespace: metallb-system
      spec:
        addresses:
          - "10.1.1.150-10.1.1.200"

    - apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        creationTimestamp: null
        name: l2advertisement1
        namespace: metallb-system
      spec:
        ipAddressPools:
          - default
