apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pulsys-hf-token
  namespace: pulsys
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: pulsys-hf-token
  data:
    - secretKey: token
      remoteRef:
        key: pulsys_pulsys-hf-token/password
