apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pulsys-pg
  namespace: pulsys
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17

  bootstrap:
    initdb:
      database: pulsys
      owner: pulsys

  storage:
    size: 5Gi
    storageClass: nfs-synology

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
