apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pulsys-cache
  namespace: pulsys
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-synology
  resources:
    requests:
      storage: 500Gi
