apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-movies
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - noatime
    - nodiratime
  nfs:
    server: 10.1.1.4
    path: /volume1/movies
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-movies
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: plex-movies
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-music
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - noatime
    - nodiratime
  nfs:
    server: 10.1.1.4
    path: /volume1/music
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-music
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: plex-music
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-pictures
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - noatime
    - nodiratime
  nfs:
    server: 10.1.1.4
    path: /volume1/pictures
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pictures
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: plex-pictures
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-tv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - noatime
    - nodiratime
  nfs:
    server: 10.1.1.4
    path: /volume1/tv
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-tv
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: plex-tv
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-audiobooks
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - noatime
    - nodiratime
  nfs:
    server: 10.1.1.4
    path: /volume1/audiobooks
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-audiobooks
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: plex-audiobooks
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-education
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - noatime
    - nodiratime
  nfs:
    server: 10.1.1.4
    path: /volume1/education
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-education
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: plex-education
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-shorts
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - noatime
    - nodiratime
  nfs:
    server: 10.1.1.4
    path: /volume1/shorts
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-shorts
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: plex-shorts
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-soundtracks
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - noatime
    - nodiratime
  nfs:
    server: 10.1.1.4
    path: /volume1/soundtracks
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-soundtracks
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: plex-soundtracks
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-data
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - noatime
    - nodiratime
  nfs:
    server: 10.1.1.4
    path: /volume1/Plex/AppData
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: plex-data
  resources:
    requests:
      storage: 500Gi
