apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-backup
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-synology
  resources:
    requests:
      storage: 50Gi
