apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: plex-high-priority
value: 1000000
globalDefault: false
preemptionPolicy: PreemptLowerPriority
description: "High priority for Plex media server"
