apiVersion: v1
kind: Secret
metadata:
  name: plex-restic-secret
  namespace: plex
type: Opaque
stringData:
  RESTIC_REPOSITORY: /backup
  RESTIC_PASSWORD: plex-volsync-backup
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: plex-config-backup
  namespace: plex
spec:
  sourcePVC: plex-config
  trigger:
    schedule: "0 */6 * * *"
  restic:
    pruneIntervalDays: 7
    repository: plex-restic-secret
    retain:
      daily: 3
      weekly: 2
    copyMethod: Direct
    moverSecurityContext:
      runAsUser: 1027
      runAsGroup: 100
    volumeMounts:
      - name: backup
        mountPath: /backup
    volumes:
      - name: backup
        persistentVolumeClaim:
          claimName: plex-config-backup
