apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-models
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.1.1.4
    path: /volume1/kubernetes/ollama
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models
  namespace: ollama
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: ollama-models
  resources:
    requests:
      storage: 500Gi
