apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: nfs-csi
spec:
  interval: 5m
  chart:
    spec:
      chart: csi-driver-nfs
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: nfs-csi
  values:
    controller:
      tolerations:
        - operator: Exists
          effect: NoSchedule
    node:
      tolerations:
        - operator: Exists
          effect: NoSchedule
