apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 5m
  chart:
    spec:
      chart: gitea
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: gitea
  valuesFrom:
    - kind: ConfigMap
      name: gitea-values
      valuesKey: values.yaml
