apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - qwen36-27b.yaml
  - qwen36-35b-a3b.yaml
  - qwen38-27b.yaml
  - podmonitor.yaml
  - open-webui.yaml
  - httproute.yaml
  - tailscale-ingress.yaml
  - external-secret.yaml
