apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: poditlater
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  metricsPath: /metrics
  scrapeInterval: 30s
  staticConfigs:
    - targets:
        - "100.103.110.56:9091"
      labels:
        job: poditlater
