apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synology-snmp
  namespace: monitoring
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: synology-snmp
  data:
    - secretKey: username
      remoteRef:
        key: monitoring_synology-snmp/username
    - secretKey: password
      remoteRef:
        key: monitoring_synology-snmp/password
