apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openclaw-home-pvc
  namespace: openclaw
  labels:
    app: openclaw
spec:
  storageClassName: nfs-synology
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
