apiVersion: v1
kind: Secret
metadata:
  name: frigate-config
  namespace: frigate
type: Opaque
stringData:
  config.yaml: |
    config: |
      logger:
        default: info
        logs:
          frigate.detector: debug
          frigate.app: debug
      mqtt:
        enabled: true
        host: "mosquitto.mqtt.svc.cluster.local"
        port: 1883
      auth:
        enabled: false
      detectors:
        onnx:
          type: onnx
          device: cuda
      model:
        model_type: yolo-generic
        width: 320
        height: 320
        input_tensor: nchw
        input_dtype: float
        path: /config/model_cache/yolov9-t-320.onnx
        labelmap_path: /labelmap/coco-80.txt
      objects:
        track:
          - person
          - dog
          - cat
      detect:
        enabled: true
        fps: 5
      snapshots:
        enabled: true
        bounding_box: true
      record:
        enabled: true
        retain:
          days: 14
      go2rtc:
        streams:
          front_door:
            - rtsp://admin:qRU4zLZPtwEJjnHqY@10.1.1.60:554/h264Preview_01_main
          rear_door:
            - rtsp://admin:qRU4zLZPtwEJjnHqY@10.1.1.62:554/h264Preview_01_main
          backyard:
            - rtsp://admin:qRU4zLZPtwEJjnHqY@10.1.1.61:554/h264Preview_01_main
      cameras:
        front_door:
          ffmpeg:
            hwaccel_args: preset-nvidia
            inputs:
              - path: rtsp://127.0.0.1:8554/front_door
                input_args: preset-rtsp-restream
                roles:
                  - detect
                  - record
        rear_door:
          ffmpeg:
            hwaccel_args: preset-nvidia
            inputs:
              - path: rtsp://127.0.0.1:8554/rear_door
                input_args: preset-rtsp-restream
                roles:
                  - detect
                  - record
        backyard:
          ffmpeg:
            hwaccel_args: preset-nvidia
            inputs:
              - path: rtsp://127.0.0.1:8554/backyard
                input_args: preset-rtsp-restream
                roles:
                  - detect
                  - record
