apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: frigate
spec:
  interval: 5m
  chart:
    spec:
      chart: frigate
      sourceRef:
        kind: HelmRepository
        name: frigate
        namespace: frigate
  values:
    image:
      tag: stable-tensorrt
    persistence:
      media:
        enabled: true
    gpu:
      nvidia:
        enabled: true
        runtimeClassName: nvidia
    resources:
      limits:
        nvidia.com/gpu: 1
    service:
      type: LoadBalancer
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "frigate"
  valuesFrom:
    - kind: Secret
      name: frigate-config
      valuesKey: config.yaml
