apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: frigate
spec:
  interval: 5m
  chart:
    spec:
      chart: frigate
      sourceRef:
        kind: HelmRepository
        name: frigate
        namespace: frigate
  values:
    persistence:
      media:
        enabled: true
  valuesFrom:
    - kind: Secret
      name: frigate-config
      valuesKey: config.yaml
