apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: frigate
spec:
  interval: 5m
  chart:
    spec:
      chart: frigate
      version: "7.8.0"
      sourceRef:
        kind: HelmRepository
        name: frigate
        namespace: frigate
  values:
    image:
      tag: 0.17.0
    persistence:
      config:
        enabled: false
      media:
        enabled: false
    extraVolumes:
      - name: config
        persistentVolumeClaim:
          claimName: frigate-config-nfs
      - name: media
        persistentVolumeClaim:
          claimName: frigate-media-nfs
    extraVolumeMounts:
      - name: config
        mountPath: /config
      - name: media
        mountPath: /media
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: google.com/edgetpu
                  operator: In
                  values:
                    - "true"
    resources:
      limits:
        google.com/edgetpu: 1
    service:
      type: LoadBalancer
      port: 80
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "frigate"
  valuesFrom:
    - kind: Secret
      name: frigate-config
      valuesKey: config.yaml
