apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reaparr-config
  namespace: reaparr
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reaparr-downloads
  namespace: reaparr
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reaparr-movies
  namespace: reaparr
spec:
  storageClassName: nfs-synology
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reaparr-tvshows
  namespace: reaparr
spec:
  storageClassName: nfs-synology
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
