apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arm-media
  namespace: arm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-synology
  resources:
    requests:
      storage: 2Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arm-music
  namespace: arm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-synology
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arm-config
  namespace: arm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
