apiVersion: v1
kind: PersistentVolume
metadata:
  name: arm-media
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - noatime
    - nodiratime
  nfs:
    server: 10.1.1.4
    path: /volume1/arm
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arm-media
  namespace: arm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: arm-media
  resources:
    requests:
      storage: 2Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arm-music
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - noatime
    - nodiratime
  nfs:
    server: 10.1.1.4
    path: /volume1/music
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arm-music
  namespace: arm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: arm-music
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arm-movies
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - noatime
    - nodiratime
  nfs:
    server: 10.1.1.4
    path: /volume1/movies
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arm-movies
  namespace: arm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: arm-movies
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arm-tv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - noatime
    - nodiratime
  nfs:
    server: 10.1.1.4
    path: /volume1/tv
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arm-tv
  namespace: arm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: arm-tv
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arm-config
  namespace: arm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
