apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtarr-downloads
  namespace: youtarr
spec:
  storageClassName: nfs-synology
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtarr-config
  namespace: youtarr
spec:
  storageClassName: nfs-synology
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtarr-db
  namespace: youtarr
spec:
  storageClassName: nfs-synology
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
