apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-app-credentials
  namespace: miniflux
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: miniflux-app-credentials
  data:
    - secretKey: username
      remoteRef:
        key: miniflux_miniflux-app-credentials/username
    - secretKey: password
      remoteRef:
        key: miniflux_miniflux-app-credentials/password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-db-credentials
  namespace: miniflux
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: miniflux-db-credentials
  data:
    - secretKey: username
      remoteRef:
        key: miniflux_miniflux-db-credentials/username
    - secretKey: password
      remoteRef:
        key: miniflux_miniflux-db-credentials/password
