apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-app-credentials
  namespace: miniflux
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: miniflux-app-credentials
  data:
    - secretKey: username
      remoteRef:
        key: miniflux/miniflux-app-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: miniflux/miniflux-app-credentials
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-db-credentials
  namespace: miniflux
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: miniflux-db-credentials
  data:
    - secretKey: username
      remoteRef:
        key: miniflux/miniflux-db-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: miniflux/miniflux-db-credentials
        property: password
