apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # - postgres.yaml  # temporarily disabled until CloudNativePG CRDs are installed
  # - miniflux.yaml  # depends on postgres
  - tailscale-ingress.yaml
