apiVersion: v1
kind: Secret
metadata:
  name: miniflux
  namespace: miniflux
type: Opaque
stringData:
  ADMIN_USERNAME: admin
  ADMIN_PASSWORD: changeme
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux
  namespace: miniflux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniflux
  template:
    metadata:
      labels:
        app: miniflux
    spec:
      containers:
        - name: miniflux
          image: miniflux/miniflux:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "postgres://miniflux:miniflux@miniflux-postgres:5432/miniflux?sslmode=disable"
            - name: RUN_MIGRATIONS
              value: "1"
            - name: CREATE_ADMIN
              value: "1"
          envFrom:
            - secretRef:
                name: miniflux
---
apiVersion: v1
kind: Service
metadata:
  name: miniflux
  namespace: miniflux
spec:
  selector:
    app: miniflux
  ports:
    - port: 8080
      targetPort: 8080
