apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp-system
spec:
  interval: 5m
  chart:
    spec:
      chart: headlamp
      version: ">=0.24.0"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: headlamp-system
  values:
    config:
      pluginsDir: /headlamp/plugins
    initContainers:
      - name: flux-plugin
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
        imagePullPolicy: Always
        command:
          - /bin/sh
          - -c
          - "mkdir -p /headlamp/plugins && cp -r /plugins/* /headlamp/plugins/ && chown -R 100:101 /headlamp/plugins"
        securityContext:
          runAsNonRoot: false
          privileged: false
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
          - mountPath: /headlamp/plugins
            name: headlamp-plugins
    volumeMounts:
      - mountPath: /headlamp/plugins
        name: headlamp-plugins
    volumes:
      - name: headlamp-plugins
        emptyDir: {}
