apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcr-cache
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcr-cache
  template:
    metadata:
      labels:
        app: gcr-cache
    spec:
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
            - containerPort: 5001
              name: metrics
          env:
            - name: REGISTRY_PROXY_REMOTEURL
              value: "https://gcr.io"
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: /var/lib/registry
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: /certs/tls.crt
            - name: REGISTRY_HTTP_TLS_KEY
              value: /certs/tls.key
            - name: REGISTRY_HTTP_DEBUG_ADDR
              value: "0.0.0.0:5001"
            - name: REGISTRY_HTTP_DEBUG_PROMETHEUS_ENABLED
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /var/lib/registry
            - name: certs
              mountPath: /certs
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gcr-cache-data
        - name: certs
          secret:
            secretName: registry-tls
---
apiVersion: v1
kind: Service
metadata:
  name: gcr-cache
  namespace: registry
  annotations:
    external-dns.alpha.kubernetes.io/hostname: gcr.cr.jgarr.net
spec:
  type: LoadBalancer
  selector:
    app: gcr-cache
  ports:
    - port: 443
      targetPort: 5000
      name: https
    - port: 5001
      targetPort: 5001
      name: metrics
