apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - cache-pvc.yaml
  - certificate.yaml
  - deployment.yaml
  - docker-cache.yaml
  - k8s-cache.yaml
  - gcr-cache.yaml
  - ghcr-cache.yaml
