apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: local-path-provisioner
spec:
  interval: 5m
  chart:
    spec:
      chart: deploy/chart/local-path-provisioner
      sourceRef:
        kind: GitRepository
        name: local-path-provisioner
        namespace: local-path-provisioner
  values:
    storageClass:
      create: true
      defaultClass: true
      name: local-path
