apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: eso-config
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/wrtk8s/external-secrets/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system
