apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-db-credentials
  namespace: paperless-ngx
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: paperless-db-credentials
  data:
    - secretKey: username
      remoteRef:
        key: paperless-ngx_paperless-db-credentials/username
    - secretKey: password
      remoteRef:
        key: paperless-ngx_paperless-db-credentials/password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-secret-key
  namespace: paperless-ngx
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: paperless-secret-key
  data:
    - secretKey: secret-key
      remoteRef:
        key: paperless-ngx_paperless-secret-key/secret-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-admin
  namespace: paperless-ngx
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: paperless-admin
  data:
    - secretKey: username
      remoteRef:
        key: paperless-ngx_paperless-admin/username
    - secretKey: password
      remoteRef:
        key: paperless-ngx_paperless-admin/password
