apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hf-token
  namespace: mistral-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: hf-token
  data:
    - secretKey: token
      remoteRef:
        key: vllm-system/hf-token
        property: token
