apiVersion: apps/v1
kind: Deployment
metadata:
  name: omni-cd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omni-cd
  template:
    metadata:
      labels:
        app: omni-cd
    spec:
      containers:
        - name: omni-cd
          image: ghcr.io/ktijssen/omni-cd:v0.1.1
          ports:
            - containerPort: 8080
          env:
            - name: REFRESH_INTERVAL
              value: "300"
            - name: LOG_LEVEL
              value: "INFO"
            - name: LOG_RETENTION_DAYS
              value: "7"
          envFrom:
            - secretRef:
                name: omni-cd-config
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: omni-cd
  namespace: default
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "omni-cd"
spec:
  type: ClusterIP
  selector:
    app: omni-cd
  ports:
    - port: 80
      targetPort: 8080
