apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tts-api-key
  namespace: tts
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: tts-api-key
  data:
    - secretKey: api-key
      remoteRef:
        key: tts/tts-api-key
        property: api-key
