apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tts-tailscale
  namespace: tts
  annotations:
    tailscale.com/funnel: "true"
spec:
  ingressClassName: tailscale
  rules:
    - host: tts
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tts
                port:
                  number: 8000
  tls:
    - hosts:
        - tts
